### PR TITLE
feature/AKK-275

### PR DESCRIPTION
**Pull request by charliemcelfresh**
https://socialcoders.atlassian.net/browse/AKK-275

Fix rspec deprecation warnings (change all occurrences of 'should' to use 'expect')

### CODE REVIEW

**Comment by hbriggs** [comment]
:+1:

**Comment by ajstiles** [comment]
Very cool.

I think the warning from mojo actually comes from the spec_helper in superbolt here - mind updating while you are in there?

https://github.com/socialchorus/superbolt/blob/eee6092b29ed399e323cd9ed968229cae5f76cc1/lib/superbolt/spec_helpers.rb#L22

**Comment by charliemcelfresh** [comment]
Done. Sheesh what a bonehead move, TY @ajstiles for catching that.

**Comment by ajstiles** [comment]
:gem:

**Pull request merged**
